import type { ProjectArea } from './types'

export const areas: ProjectArea[] = [
  {
    slug: 'papagou',
    area: { el: 'Παπάγου' },
    buildings: [
      {
        address: { el: 'ΧΕΙΜΑΡΡΑΣ 36, ΠΑΠΑΓΟΥ', en: '36 CHEIMARRAS ST, PAPAGOU' },
        specs: { el: 'ΤΕΤΡΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ, ΓΚΑΡΑΖ, ΣΟΦΙΤΑ, ΣΤΕΓΗ & ΔΩΜΑ', en: 'FOUR-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT, GARAGE, ATTIC, PITCHED ROOF & ROOF TERRACE' },
        description: { el: 'Σύγχρονο κτήριο σε πολύ ήσυχο σημείο στην περιοχή του Παπάγου. Ο σχεδιασμός του κτηρίου βασίζεται στην βέλτιστη αξιοποίηση του οικοπέδου και του προσανατολισμού. Αποτελείται από τέσσερις ορόφους και συνολικά πέντε διαμερίσματα. Στο τελευταίο επίπεδο βρίσκεται μια μεζονέτα, τα χαρακτηριστικά της οποίας παρουσιάζονται στο παρακάτω σχέδιο.', en: 'A contemporary building on a very quiet spot in Papagou. The design makes the best possible use of the plot and its orientation. It has four floors and five apartments in total. On the top level there is a maisonette, whose features are shown in the drawing below.' },
      },
      {
        address: { el: 'ΕΘΝΙΚΗΣ ΑΜΥΝΗΣ 1, ΠΑΠΑΓΟΥ', en: '1 ETHNIKIS AMYNIS AVE, PAPAGOU' },
        specs: { el: 'ΠΕΝΤΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ & ΔΩΜΑ', en: 'FIVE-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT & ROOF TERRACE' },
      },
    ],
    images: [
      '/images/papagou/01.jpg',
      '/images/papagou/02.jpg',
      '/images/papagou/03.jpg',
      '/images/papagou/04.jpg',
      '/images/papagou/05.jpg',
      '/images/papagou/06.jpg',
      '/images/papagou/07.jpg',
      '/images/papagou/08.jpg',
      '/images/papagou/09.jpg',
      '/images/papagou/10.jpg',
    ],
  },
  {
    slug: 'xolargos',
    area: { el: 'Χολαργός' },
    buildings: [
      {
        address: { el: 'ΠΥΘΑΓΟΡΑ 20, ΧΟΛΑΡΓΟΣ', en: '20 PYTHAGORA ST, CHOLARGOS' },
        specs: { el: 'ΤΕΤΡΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ & ΔΩΜΑ', en: 'FOUR-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT & ROOF TERRACE' },
        description: { el: 'Πρόκειται για ένα κτήριο κατοικιών τοποθετημένο στην περιοχή του Χολαργού. Με σύμμαχο τον άριστο προσανατολισμό, δημιουργήθηκε ένα κτήριο με λευκά γραμμικά οριζόντια στοιχεία και ξύλινα περσιδωτά χωρίσματα. Η μέγιστη ενεργειακή κατάταξη του κτηρίου επιτυγχάνεται με την χρήση ενεργειακών κουφωμάτων, ηλιακών συλλεκτών, θερμοπρόσοψης 10εκ., καθώς και αντλιών θερμότητας ψύξης θέρμανσης.', en: 'A residential building in Cholargos. With an excellent orientation on its side, it was built with white linear horizontal elements and wooden louvred screens. The building reaches the top energy rating through energy-efficient frames, solar collectors, 10 cm external wall insulation, and heat pumps for cooling and heating.' },
      },
      {
        address: { el: 'ΑΝΑΣΤΑΣΕΩΣ 55, ΧΟΛΑΡΓΟΣ', en: '55 ANASTASEOS ST, CHOLARGOS' },
        specs: { el: 'ΤΕΤΡΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ & ΔΩΜΑ', en: 'FOUR-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT & ROOF TERRACE' },
      },
    ],
    images: [
      '/images/xolargos/01.jpg',
      '/images/xolargos/02.jpg',
      '/images/xolargos/03.jpg',
      '/images/xolargos/04.jpg',
      '/images/xolargos/05.jpg',
      '/images/xolargos/06.jpg',
      '/images/xolargos/07.jpg',
      '/images/xolargos/08.jpg',
    ],
  },
  {
    slug: 'zografou',
    area: { el: 'Ζωγράφου' },
    buildings: [
      {
        address: { el: 'ΛΟΧΑΓΟΥ ΓΙΑΝΝΟΠΟΥΛΟΥ 11, ΖΩΓΡΑΦΟΥ', en: '11 LOCHAGOU GIANNOPOULOU ST, ZOGRAFOU' },
        specs: { el: 'ΕΞΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ, ΓΚΑΡΑΖ, ΠΑΤΑΡΙ & ΔΩΜΑ', en: 'SIX-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT, GARAGE, MEZZANINE & ROOF TERRACE' },
      },
    ],
    images: [
      '/images/zografou/01.jpg',
    ],
  },
  {
    slug: 'nikea',
    area: { el: 'Νίκαια' },
    buildings: [
      {
        address: { el: 'ΑΔΡΑΜΥΤΙΟΥ 15, ΝΙΚΑΙΑ', en: '15 ADRAMYTIOU ST, NIKAIA' },
        specs: { el: 'ΠΕΝΤΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ & ΔΩΜΑ', en: 'FIVE-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT & ROOF TERRACE' },
      },
    ],
    images: [
      '/images/nikea/01.jpg',
      '/images/nikea/02.jpg',
      '/images/nikea/03.jpg',
    ],
  },
  {
    slug: 'keratsini',
    area: { el: 'Κερατσίνι' },
    buildings: [
      {
        address: { el: 'ΔΕΛΦΩΝ 13 & ΙΘΑΚΗΣ, ΚΕΡΑΤΣΙΝΙ', en: '13 DELFON ST & ITHAKIS ST, KERATSINI' },
        specs: { el: 'ΠΕΝΤΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ & ΔΩΜΑ', en: 'FIVE-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT & ROOF TERRACE' },
      },
    ],
    images: [
      '/images/keratsini/01.jpg',
    ],
  },
  {
    slug: 'agia-paraskevi',
    area: { el: 'Αγία Παρασκευή' },
    buildings: [
      {
        address: { el: 'ΤΕΡΨΙΘΕΑΣ 27, ΑΓ. ΠΑΡΑΣΚΕΥΗ', en: '27 TERPSITHEAS ST, AGIA PARASKEVI' },
        specs: { el: 'ΠΕΝΤΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ.', en: 'FIVE-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT.' },
        description: { el: 'Σύγχρονο κτήριο σε πολύ ήσυχο σημείο στην περιοχή της Αγίας Παρασκευής. Ο σχεδιασμός του κτιρίου βασίζεται στην βέλτιστη αξιοποίηση του οικοπέδου και του προσανατολισμού. Αποτελείται από πέντε ορόφους και συνολικά εφτά διαμερίσματα.', en: 'A contemporary building on a very quiet spot in Agia Paraskevi. The design makes the best possible use of the plot and its orientation. It has five floors and seven apartments in total.' },
      },
    ],
    images: [
      '/images/agia-paraskevi/01.jpg',
      '/images/agia-paraskevi/02.jpg',
      '/images/agia-paraskevi/03.jpg',
      '/images/agia-paraskevi/04.jpg',
      '/images/agia-paraskevi/05.jpg',
      '/images/agia-paraskevi/06.jpg',
      '/images/agia-paraskevi/07.jpg',
      '/images/kouzines/27.jpg',
      '/images/kouzines/28.jpg',
      '/images/agia-paraskevi/10.jpg',
      '/images/kouzines/30.jpg',
      '/images/agia-paraskevi/12.jpg',
      '/images/kouzines/29.jpg',
      '/images/kouzines/32.jpg',
      '/images/agia-paraskevi/15.jpg',
      '/images/kouzines/34.jpg',
      '/images/agia-paraskevi/17.jpg',
      '/images/kouzines/33.jpg',
      '/images/wc/25.jpg',
      '/images/agia-paraskevi/20.jpg',
      '/images/upnodomatia/33.jpg',
      '/images/wc/27.jpg',
      '/images/agia-paraskevi/23.jpg',
      '/images/wc/21.jpg',
      '/images/wc/22.jpg',
      '/images/wc/23.jpg',
      '/images/wc/29.jpg',
      '/images/wc/28.jpg',
      '/images/wc/24.jpg',
      '/images/upnodomatia/28.jpg',
      '/images/upnodomatia/30.jpg',
      '/images/upnodomatia/29.jpg',
      '/images/upnodomatia/31.jpg',
      '/images/agia-paraskevi/34.jpg',
      '/images/agia-paraskevi/35.jpg',
      '/images/agia-paraskevi/36.png',
      '/images/upnodomatia/32.jpg',
      '/images/agia-paraskevi/38.jpg',
      '/images/agia-paraskevi/39.jpg',
      '/images/agia-paraskevi/40.jpg',
      '/images/agia-paraskevi/41.jpg',
    ],
  },
  {
    slug: 'peukh',
    area: { el: 'Πεύκη' },
    buildings: [
      {
        address: { el: 'ΚΩΝΣΤΑΝΤΙΝΟΥΠΟΛΕΩΣ 67, ΠΕΥΚΗ', en: '67 KONSTANTINOUPOLEOS ST, PEFKI' },
        specs: { el: 'ΤΕΤΡΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΕΠΙ PILOTIS ΜΕ ΥΠΟΓΕΙΟ & ΠΑΤΑΡΙ.', en: 'FOUR-STOREY APARTMENT BUILDING ON PILOTIS WITH BASEMENT & MEZZANINE.' },
        description: { el: 'Σύγχρονο κτήριο σε πολύ ήσυχο σημείο στην περιοχή της Πεύκης. Διαθέτει ένα διαμέρισμα ανά όροφο, υπόγειες αποθήκες και ισόγειες θέσεις στάθμευσης.', en: 'A contemporary building on a very quiet spot in Pefki. One apartment per floor, storage rooms in the basement and parking spaces at ground level.' },
      },
    ],
    images: [
      '/images/peukh/01.jpg',
      '/images/peukh/02.jpg',
      '/images/peukh/03.jpg',
      '/images/peukh/04.jpg',
      '/images/peukh/05.jpg',
      '/images/peukh/06.jpg',
      '/images/peukh/07.jpg',
      '/images/peukh/08.jpg',
      '/images/peukh/09.jpg',
      '/images/peukh/10.jpg',
      '/images/peukh/11.jpg',
      '/images/peukh/12.jpg',
      '/images/peukh/13.jpg',
      '/images/peukh/14.jpeg',
      '/images/peukh/15.jpg',
      '/images/peukh/16.jpg',
      '/images/peukh/17.jpg',
      '/images/peukh/18.jpg',
      '/images/peukh/19.jpg',
      '/images/peukh/20.jpg',
      '/images/peukh/21.jpg',
      '/images/peukh/22.jpg',
      '/images/peukh/23.jpg',
      '/images/peukh/24.jpg',
      '/images/peukh/25.jpg',
      '/images/peukh/26.jpg',
      '/images/peukh/27.jpg',
      '/images/peukh/28.jpg',
      '/images/peukh/29.jpg',
      '/images/peukh/30.jpg',
      '/images/peukh/31.jpg',
      '/images/peukh/32.jpg',
      '/images/peukh/33.jpg',
      '/images/peukh/34.jpg',
      '/images/peukh/35.jpg',
      '/images/peukh/36.jpg',
      '/images/peukh/37.jpg',
      '/images/peukh/38.jpg',
      '/images/peukh/39.jpg',
      '/images/peukh/40.jpg',
      '/images/peukh/41.jpg',
      '/images/peukh/42.jpg',
    ],
  },
  {
    slug: 'palaio-faliro',
    area: { el: 'Παλαιό Φάληρο' },
    buildings: [
      {
        address: { el: 'ΑΙΑΝΤΟΣ 81, ΠΑΛΑΙΟ ΦΑΛΗΡΟ', en: '81 AIANTOS ST, PALAIO FALIRO' },
        specs: { el: 'ΝΕΑ ΕΠΤΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ME PILOTIS, ΥΠΟΓΕΙΟ ΚΑΙ ΔΩΜΑ', en: 'NEW SEVEN-STOREY APARTMENT BUILDING WITH PILOTIS, BASEMENT AND ROOF TERRACE' },
        description: { el: 'Σύγχρονο κτήριο σε εύκολα προσβάσιμο σημείο στην περιοχή του Παλαιού φαλήρου. Διαθέτει επτά ορόφους και έξι διαμερίσματα, υπόγειες αποθήκες και ισόγειες και υπόγειες θέσεις στάθμευσης.', en: 'A contemporary building in an easily reached part of Palaio Faliro. It has seven floors and six apartments, storage rooms in the basement, and parking spaces at ground level and below.' },
      },
    ],
    images: [
      '/images/palaio-faliro/01.jpg',
      '/images/palaio-faliro/02.jpg',
      '/images/palaio-faliro/03.jpg',
      '/images/palaio-faliro/04.jpg',
      '/images/palaio-faliro/05.jpg',
      '/images/palaio-faliro/06.jpg',
      '/images/palaio-faliro/07.jpg',
      '/images/palaio-faliro/08.jpg',
      '/images/palaio-faliro/09.jpg',
      '/images/palaio-faliro/10.jpg',
      '/images/palaio-faliro/11.jpg',
      '/images/palaio-faliro/12.jpg',
      '/images/palaio-faliro/13.jpg',
      '/images/palaio-faliro/14.jpg',
      '/images/palaio-faliro/15.jpg',
      '/images/palaio-faliro/16.jpg',
      '/images/palaio-faliro/17.jpg',
      '/images/palaio-faliro/18.jpg',
      '/images/palaio-faliro/19.jpg',
      '/images/palaio-faliro/20.jpg',
      '/images/palaio-faliro/21.jpg',
      '/images/palaio-faliro/22.jpg',
    ],
  }
]
