import type { Interior } from './types'

export const interiors: Interior[] = [
  {
    slug: 'saloni',
    title: { el: 'Σαλόνια', en: 'Living rooms' },
    images: [
      '/images/saloni/01.jpg',
      '/images/saloni/02.jpg',
      '/images/saloni/03.jpg',
      '/images/saloni/04.jpg',
      '/images/saloni/05.jpg',
      '/images/saloni/06.jpg',
      '/images/saloni/07.jpg',
      '/images/saloni/08.jpg',
      '/images/saloni/09.jpg',
      '/images/saloni/10.jpg',
      '/images/saloni/11.jpg',
      '/images/saloni/12.jpg',
      '/images/saloni/13.jpg',
      '/images/saloni/14.jpg',
      '/images/saloni/15.jpg',
      '/images/saloni/16.jpg',
      '/images/saloni/17.jpg',
      '/images/saloni/18.jpg',
      '/images/saloni/19.jpg',
      '/images/saloni/20.jpg',
      '/images/saloni/21.jpg',
    ],
  },
  {
    slug: 'kouzines',
    title: { el: 'Κουζίνες', en: 'Kitchens' },
    images: [
      '/images/kouzines/01.jpg',
      '/images/kouzines/02.jpg',
      '/images/kouzines/03.jpg',
      '/images/kouzines/04.jpg',
      '/images/kouzines/05.jpg',
      '/images/kouzines/06.jpg',
      '/images/kouzines/07.jpg',
      '/images/kouzines/08.jpg',
      '/images/kouzines/09.jpg',
      '/images/kouzines/10.jpg',
      '/images/kouzines/11.jpg',
      '/images/kouzines/12.jpg',
      '/images/kouzines/13.jpg',
      '/images/kouzines/14.jpg',
      '/images/kouzines/15.jpg',
      '/images/kouzines/16.jpg',
      '/images/kouzines/17.jpg',
      '/images/kouzines/18.jpg',
      '/images/kouzines/19.jpg',
      '/images/kouzines/20.jpg',
      '/images/kouzines/21.jpg',
      '/images/kouzines/22.jpg',
      '/images/kouzines/23.jpg',
      '/images/kouzines/24.jpg',
      '/images/kouzines/25.jpg',
      '/images/kouzines/26.jpg',
      '/images/kouzines/27.jpg',
      '/images/kouzines/28.jpg',
      '/images/kouzines/29.jpg',
      '/images/kouzines/30.jpg',
      '/images/kouzines/31.png',
      '/images/kouzines/32.jpg',
      '/images/kouzines/33.jpg',
      '/images/kouzines/34.jpg',
    ],
  },
  {
    slug: 'wc',
    title: { el: 'Μπάνια', en: 'Bathrooms' },
    images: [
      '/images/wc/01.jpg',
      '/images/wc/02.jpg',
      '/images/wc/03.jpg',
      '/images/wc/04.jpg',
      '/images/wc/05.jpg',
      '/images/wc/06.jpg',
      '/images/wc/07.jpg',
      '/images/wc/08.jpg',
      '/images/wc/09.jpg',
      '/images/wc/10.jpg',
      '/images/wc/11.jpg',
      '/images/wc/12.jpg',
      '/images/wc/13.jpg',
      '/images/wc/14.jpg',
      '/images/wc/15.jpg',
      '/images/wc/16.jpg',
      '/images/wc/17.jpg',
      '/images/wc/18.jpg',
      '/images/wc/19.jpg',
      '/images/wc/20.jpg',
      '/images/wc/21.jpg',
      '/images/wc/22.jpg',
      '/images/wc/23.jpg',
      '/images/wc/24.jpg',
      '/images/wc/25.jpg',
      '/images/wc/26.jpg',
      '/images/wc/27.jpg',
      '/images/wc/28.jpg',
      '/images/wc/29.jpg',
    ],
  },
  {
    slug: 'upnodomatia',
    title: { el: 'Υπνοδωμάτια', en: 'Bedrooms' },
    images: [
      '/images/upnodomatia/01.jpg',
      '/images/upnodomatia/02.jpg',
      '/images/upnodomatia/03.jpg',
      '/images/upnodomatia/04.jpg',
      '/images/upnodomatia/05.jpg',
      '/images/upnodomatia/06.jpg',
      '/images/upnodomatia/07.jpg',
      '/images/upnodomatia/08.jpg',
      '/images/upnodomatia/09.jpg',
      '/images/upnodomatia/10.jpg',
      '/images/upnodomatia/11.jpg',
      '/images/upnodomatia/12.jpg',
      '/images/upnodomatia/13.jpg',
      '/images/upnodomatia/14.jpg',
      '/images/upnodomatia/15.jpg',
      '/images/upnodomatia/16.jpg',
      '/images/upnodomatia/17.jpg',
      '/images/upnodomatia/18.jpg',
      '/images/upnodomatia/19.jpg',
      '/images/upnodomatia/20.jpg',
      '/images/upnodomatia/21.jpg',
      '/images/upnodomatia/22.jpg',
      '/images/upnodomatia/23.jpg',
      '/images/upnodomatia/24.jpg',
      '/images/upnodomatia/25.jpg',
      '/images/upnodomatia/26.jpg',
      '/images/upnodomatia/27.jpg',
      '/images/upnodomatia/28.jpg',
      '/images/upnodomatia/29.jpg',
      '/images/upnodomatia/30.jpg',
      '/images/upnodomatia/31.jpg',
      '/images/upnodomatia/32.jpg',
      '/images/upnodomatia/33.jpg',
    ],
  }
]
